### ISSUE TITLE
Proposal: CI/CD abstraction

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade-github-gateway#4]
It's not as easy as it _could_ be to combine this gateway with Brigade 2 to roll your own CI/CD system.

To demonstrate, we'll consider Brigade 2's use of itself and of this gateway to effect its own CI/CD.

Consider these event subscriptions in the project definition:

```
eventSubscriptions:
- qualifiers:
    repo: brigadecore/brigade
  source: brigade.sh/github
  types:
  - check_run:rerequested
  - check_suite:requested
  - check_suite:rerequested
```

This says the project is subscribed to events from this gateway, provided they're related to the `brigadecore/brigade` repository. All of this is reasonably intuitive.

But the project subscribes to three specific event types, namely:

* `check_run:rerequested`
* `check_suite:requested`
* `check_suite:rerequested`
* `push`

The problem with _this_ is that, not only is it not intuitive to write, it's also not intuitively understood when read unless one has already worked extensively with GitHub APIs-- and that's not most people. Users won't want to chase down documentation to understand how these events relate to the typical CI workflow (PR --> test --> merge --> re-test) or the typical CD workflow (tag --> release or deploy).

To demonstrate the nuances at work, a `check_suite:requested` event might have been issued by GitHub in response to a push / merge to a particular branch. But that it _also_ could have occurred because a PR was opened. Brigade's own CI/CD needs to distinguish between these two scenarios because when a PR is opened or synced, we only want to test, but when a PR is merged, we want to repeat the tests and _also_ publish "edge" images. We end up writing code in our `brigade.ts` to address this:

```
// Run the entire suite of tests WITHOUT publishing anything initially. If
// EVERYTHING passes AND this was a push (merge, presumably) to the v2 branch,
// then run jobs to publish "edge" images.
async function runSuite(event: Event): Promise<void> {
  await new SerialGroup(
    // First batch of tasks ...
  ).run()
  if (event.worker?.git?.ref == "/refs/heads/v2") {
    // Push "edge" images
    await new ConcurrentGroup(
      // Second, conditional batch of tasks ...
    ).run()
  }
}

// Either of these events should initiate execution of the entire test suite.
events.on("brigade.sh/github", "check_suite:requested", runSuite)
events.on("brigade.sh/github", "check_suite:rerequested", runSuite)
```

When `event.worker?.git?.ref == "/refs/heads/v2"`, we infer that the `check_suite:requested` or `check_suite:rerequested` event we received was in response to a merge to the `v2` branch, rather than the result of an opened or synced PR.

Similarly, for a `push` event, we write code to distinguish between pushes we can ignore because they should presumably have _also_ resulted in a `check_suite:requested` event that we're already handling, vs "pushes" that are really just a new tag applied to an existing commit. And more specifically, we're only interested in tags that are semver tags:

```
// Pushing new commits to any branch in github triggers a check suite. Such
// events are already handled above. Here we're only concerned with the case
// wherein a new TAG has been pushed-- and even then, we're only concerned with
// tags that look like a semantic version and indicate a formal release should
// be performed.
events.on("brigade.sh/github", "push", async event => {
  const matchStr = event.worker.git.ref.match(releaseTagRegex)
  if (matchStr) {
    // This is an official release with a semantically versioned tag
    await new SerialGroup(
      new ConcurrentGroup(
        // Tasks ...
      )
    ).run()
  } else {
    console.log(`Ref ${event.worker.git.ref} does not match release tag regex (${releaseTagRegex}); not releasing.`)
  }
})
```

**_BUT_** if we can write code in our script to distinguish between like events based on their details, we could incorporate similar code directly into the gateway so that the gateway handles this nonsense and emits events that are more semantically meaningful and intuitive for someone who's just looking to do CI/CD.

For example, if the gateway were to dig into the details of a `check_suite:rerequested` event and find that it's associated with a pull request, something like a `pr:test` event could be emitted. If, instead, it's determined to have resulted from a recent merge, a `pr:merged` event could be emitted. This could even be tagged with the name of the branch, which would allow subscribers to subscribe only to merges to specific branches!

Still, by way of example, the gateway could dig into the details of a `push` event and discover that it was a _tag_ that was pushed, and that, furthermore, the tag is a semver tag. This could result in the emission of something like a `release` event.

Were the gateway to do all this work, a project's event subscriptions might look more like this:

```
eventSubscriptions:
- source: brigade.sh/github
  qualifiers:
    repo: brigadecore/brigade
  types:
  - pr:test
  - release
- source: brigade.sh/github
  qualifiers:
    repo: brigadecore/brigade
  tags:
    branch: v2
  types:
  - pr:merge
```

This _very clearly_ expresses an interest in testing PRs opened in `brigadecore/brigade` repository, re-testing the contents of the `v2` branch (and only that branch) post-merge, and executing some kind release process when a release occurs.

What's even better, is that the corresponding `brigade.ts` can lose all the logic that previously dug through more obscure event types to glean details.

**Comment by vdice** [comment]
👍 
> What's even better, is that the corresponding brigade.ts can lose all the logic that previously dug through more obscure event types to glean details.

In general, I'm always in support of efforts that aim to reduce the amount of code/logic needed in a brigade script to perform common tasks like this, so I think this would be great.  The envisioned method of declaring the types of events to subscribe to and their corresponding branches/tags seems straightforward on first glance.  Thumbs up from me!

**Comment by vdice** [comment]
A note to capture a side discussion around parsing check run rerequested events, which come in w/ names formatted like `<project name>:<check name>` (sample PR to do the parsing in a Brigade script here: https://github.com/brigadecore/brigade/pull/1482)

@krancour and I mentioned how it might be nice to add some logic in this effort to prevent the need for explicit parsing in a Brigade script... something along the lines of 'raw' check run name (full name from GH) and 'parsed'/'casual' check run name (just the check name sans project name).

**Comment by krancour** [comment]
@vdice thanks for making the effort to capture our side discussion so we don't lose track of it.
